name: Docker Image CI

on:
  push:
    branches: [ "devcontainer" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build the ReactJS Docker image
        run: |
          TAG=$(date +%s)
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_NAME }}:${TAG}
          docker save ${{ secrets.DOCKER_NAME }}:${TAG} > ${{ secrets.DOCKER_NAME }}.tar

      - name: scp the ReactJS Docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ secrets.DOCKER_NAME }}.tar"
          target: "/tmp/${{ secrets.DOCKER_NAME }}"

      # ssh to the server and run the commands
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker load -i /tmp/${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_NAME }}.tar
