name: Docker Image CI

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup firebaseConfig.json
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'firebaseConfig.json'
          fileDir: './src/conf/'
          encodedString: ${{ secrets.FIREBASECONFIG }}
      
      - name: Setup apiConf.json
        uses: timheuer/base64-to-file@v1.2
        with:
          fileName: 'apiConf.json'
          fileDir: './src/conf/'
          encodedString: ${{ secrets.APICONF }}

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Install dependencies
        run: yarn install

      - name: Build the ReactJS app
        run: npx react-scripts build --ignore-warnings

      - name: Update Nginx config
        run: |
          sed -i 's|ssl_certificate     www.example.com.crt;|ssl_certificate ${CERTIFICATE};|g' nginx.conf
          sed -i 's|ssl_certificate_key www.example.com.key;|ssl_certificate_key ${CERTIFICATE_KEY};|g' nginx.conf

      - name: Build the ReactJS Docker image
        run: |
          TAG=$(git describe --tags)
          docker build . --file Dockerfile --tag ${{ secrets.DOCKER_NAME }}:${TAG}
          docker save ${{ secrets.DOCKER_NAME }}:${TAG} > ${{ secrets.DOCKER_NAME }}.tar

      - name: scp the ReactJS Docker image
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "${{ secrets.DOCKER_NAME }}.tar"
          target: "/tmp/${{ secrets.DOCKER_NAME }}"

      # ssh to the server and run the commands
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            IMAGE_ID=$(docker load -i /tmp/${{ secrets.DOCKER_NAME }}/${{ secrets.DOCKER_NAME }}.tar | awk '/Loaded image:/ {print $3}')
            docker tag ${IMAGE_ID} ${{ secrets.DOCKER_NAME }}:latest
            cd /home/eaas/
            docker-compose up -d --build EaaS-ReactJS-Service
